baseURL = "https://apertium-tradumatica2018.netlify.com/"
languageCode = "ca"
defaultContentLanguage = "ca"
title = "Apertium: traducció automàtica lliure per a tothom"
theme = "learn"

[params]
sidebarColor = "orange"
disableSearch = true
themeVariant = "mine"

[[menu.shortcuts]]
name = "Lloc web d'Apertium"
url = "https://www.apertium.org"
weight = 10

[[menu.shortcuts]]
name = "Documentació d'Apertium"
url = "https://wiki.apertium.org"
weight = 20

[[menu.shortcuts]]
name = "Codi font d'Apertium"
url = "https://www.github.com/apertium"
weight = 30
